extends Node

var vocab = {
	"Artery" : "A vessel that carries blood away from the heart to organs throughout the body.",
	"Vein" : "In animals, a vessel that carries blood toward the heart.",
	"Endothelium" : "The simple squamous layer of cells lining the lumen of blood vessels.",
	"Gastrovascular Cavity" : "A central cavity with a single opening in the body of certain animals, including cnidarians and flatworms, that functions in both the digestion and distribution of nutrients.",
	"Pulse" : "The rhythmic bulging of the artery walls with each heartbeat.",
	"Erythrocyte" : "A blood cell that contains hemoglobin, which transports oxygen; also called a red blood cell.",
	"Alveoli" : "One of the dead-end air sacs where gas exchange occurs in a mammalian lung.",
	"Electrocardiogram (ECG or EKG)" : "A record of the electrical impulses that travel through heart muscle during the cardiac cycle.",
	"Closed Circulatory System" : "A circulatory system in which blood is confined to vessels and is kept separate from the interstitial fluid.",
	"Tracheal System" : "In insects, a system of branched, air-filled tubes that extends throughout the body and carries oxygen directly to cells.",
	"Double Circulation" : "A circulatory system consisting of separate pulmonary and systemic circuits, in which blood passes through the heart after completing each circuit.",
	"Platelet" : "A pinched-off cytoplasmic fragment of a specialized bone marrow cell. Platelets circulate in the blood and are important in blood clotting.",
	"Stem Cell" : "Any relatively unspecialized cell that can produce, during a single division, two identical daughter cells or two more specialized daughter cells that can undergo further differentiation, or one cell of each type.",
	"Diaphragm" : "A sheet of muscle that forms the bottom wall of the thoracic cavity in mammals. Contraction of the diaphragm pulls air into the lungs.",
	"Sickle-cell Disease" : "A recessively inherited human blood disorder in which a single nucleotide change in the β-globin gene causes hemoglobin to aggregate, changing red blood cell shape and causing multiple symptoms in afflicted individuals.",
	"Breathing" : "Ventilation of the lungs through alternating inhalation and exhalation.",
	"Heart" : "A muscular pump that uses metabolic energy to elevate the hydrostatic pressure of the circulatory fluid (blood or hemolymph). The fluid then flows down a pressure gradient through the body and eventually returns to the heart.",
	"Semilunar Valve" : "A valve located at each exit of the heart, where the aorta leaves the left ventricle and the pulmonary artery leaves the right ventricle.",
	"Ventilation" : "The flow of air or water over a respiratory surface.",
	"Atrium" : "(plural, atria) A chamber of the vertebrate heart that receives blood from the veins and transfers blood to a ventricle.",
	"Gas Exchange" : "The uptake of molecular oxygen from the environment and the discharge of carbon dioxide to the environment.",
	"Bronchus" : "(plural, Bronchi) One of a pair of breathing tubes that branch from the trachea into the lungs.",
	"Blood" : "A connective tissue with a fluid matrix called plasma in which red blood cells, white blood cells, and cell fragments called platelets are suspended.",
	"Respiratory pigment" : "A protein that transports oxygen in blood or hemolymph.",
	"Thrombus" : "A fibrin-containing clot that forms in a blood vessel and blocks the flow of blood.",
	"Ventricle" : "A heart chamber that pumps blood out of the heart.",
	"Tidal Volume" : "The volume of air a mammal inhales and exhales with each breath.",
	"Negative Pressure Breathing" : "A breathing system in which air is pulled into the lungs.",
	"Residual Volume" : "The amount of air that remains in the lungs after forceful exhalation.",
	"Vital Capacity" : "The maximum volume of air that a mammal can inhale and exhale with each breath.",
	"Open Circulatory System" : "A circulatory system in which fluid called hemolymph bathes the tissues and organs directly and there is no distinction between the circulating fluid and the interstitial fluid.",
	"Lymph" : "The colorless fluid, derived from interstitial fluid, in the lymphatic system of vertebrates.",
	"Diffusion" : "The random thermal motion of particles of liquids, gases, or solids. In the presence of a concentration or electrochemical gradient, diffusion results in the net movement of a substance from a region where it is more concentrated to a region where it is less concentrated.",
	"Countercurrent Exchange" : "The exchange of a substance or heat between two fluids flowing in opposite directions. For example, blood in a fish gill flows in the opposite direction of water passing over the gill, maximizing diffusion of oxygen into and carbon dioxide out of the blood.",
	"Hemolymph" : "In invertebrates with an open circulatory system, the body fluid that bathes tissues.",
	"Heart Attack" : "The damage or death of cardiac muscle tissue resulting from prolonged blockage of one or more coronary arteries.",
	"Hemoglobin" : "An iron-containing protein in red blood cells that reversibly binds oxygen.",
	"Atherosclerosis" : "A cardiovascular disease in which fatty deposits called plaques develop in the inner walls of the arteries, obstructing the arteries and causing them to harden.",
	"Trachea" : "The portion of the respiratory tract that passes from the larynx to the bronchi; also called the windpipe.",
	"Leukocyte" : "A blood cell that functions in fighting infections; also called a white blood cell.",
	"Positive Pressure Breathing" : "A breathing system in which air is forced into the lungs.",
	"Vasodilation" : "An increase in the diameter of blood vessels caused by relaxation of smooth muscles in the vessel walls.",
	"Hypertension" : "A disorder in which blood pressure remains abnormally high.",
	"Surfactant" : "A substance secreted by alveoli that decreases surface tension in the fluid that coats the alveoli.",
	"Capillaries" : "A microscopic blood vessel that penetrates the tissues and consists of a single layer of endothelial cells that allows exchange between the blood and interstitial fluid.",
	"Vasoconstriction" : "A decrease in the diameter of blood vessels caused by contraction of smooth muscles in the vessel walls.",
	"Diastole" : "The stage of the cardiac cycle in which a heart chamber is relaxed and fills with blood.",
	"Atrioventricular (AV) Node" : "A region of specialized heart muscle tissue between the left and right atria where electrical impulses are delayed for about 0.1 second before spreading to both ventricles and causing them to contract.",
	"Stroke" : "The death of nervous tissue in the brain, usually resulting from rupture or blockage of arteries in the neck or head.",
	"Larynx" : "The portion of the respiratory tract containing the vocal cords; also called the voice box.",
	"Single Circulation" : "A circulatory system consisting of a single pump and circuit, in which blood passes from the sites of gas exchange to the rest of the body before returning to the heart.",
	"Lymph Node" : "An organ located along a lymph vessel. Lymph nodes filter lymph and contain cells that attack viruses and bacteria.",
	"Partial Pressure" : "The pressure exerted by a particular gas in a mixture of gases (for instance, the pressure exerted by oxygen in air).",
	"Plasma" : "The liquid matrix of blood in which the blood cells are suspended.",
	"Sinoatrial (SA) Node" : "A region in the right atrium of the heart that sets the rate and timing at which all cardiac muscle cells contract; the pacemaker.",
	"Lymphatic System" : "A system of vessels and nodes, separate from the circulatory system, that returns fluid, proteins, and cells to the blood.",
	"Systole" : "The stage of the cardiac cycle in which a heart chamber contracts and pumps blood.",
	"Bohr Shift" : "A lowering of the affinity of hemoglobin for oxygen, caused by a drop in pH. It facilitates the release of oxygen from hemoglobin in the vicinity of active tissues.",
	"Lung" : "An infolded respiratory surface of a terrestrial vertebrate, land snail, or spider that connects to the atmosphere by narrow tubes.",
	"Atrioventricular (AV) Valve" : "A heart valve located between each atrium and ventricle that prevents a backflow of blood when the ventricle contracts.",
	"Low-Density Lipoprotein (LDL)" : "A particle in the blood made up of thousands of cholesterol molecules and other lipids bound to a protein. LDL transports cholesterol from the liver for incorporation into cell membranes.",
	"Cardiac Cycle" : "The alternating contractions and relaxations of the heart.",
	"Myoglobin" : "An oxygen- storing, pigmented protein in muscle cells.",
	"High-Density Lipoprotein (HDL)" : "A particle in the blood made up of thousands of cholesterol molecules and other lipids bound to a protein. HDL scavenges excess cholesterol."
}

var current_vocab = []
